# Generated by Django 5.0.3 on 2024-04-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_semester_remove_course_id_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
