# Generated by Django 5.0.3 on 2024-04-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_enrollment_grade_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='staff_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
