# Generated by Django 5.0.3 on 2024-04-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_teaching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
    ]
