# Generated by Django 5.0.3 on 2024-04-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_student_course_remove_student_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.semester'),
        ),
    ]
