# Generated by Django 5.0.3 on 2024-05-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_teaching_course_alter_teaching_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
