# Generated by Django 5.0.3 on 2024-06-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_enrollment_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together={('lecturer', 'course', 'semester')},
        ),
    ]
